const parcels = [
  {
    parcelId: 11,
    user: {
      id: 1,
    },
    parcelName: 'Iphone X',
    status: 'delivered',
    location: 'Uganda',
    destination: 'Kenya',
    weight: 10,
    price: 200,
  },
  {
    parcelId: 13,
    user: {
      id: 1,
    },
    parcelName: 'Beats Speaker',
    status: 'cancelled',
    location: 'Nigeria',
    destination: 'Kenya',
    weight: 10,
    price: 200,
  },
  {
    parcelId: 12,
    user: {
      id: 1,
    },
    parcelName: 'Amazon Kindle',
    status: 'in transit',
    location: 'Uganda',
    destination: 'Kenya',
    weight: 10,
    price: 200,
  },
  {
    parcelId: 21,
    user: {
      id: 2,
    },
    parcelName: 'Apple MacBook Pro',
    status: 'in transit',
    location: 'Rwanda',
    destination: 'Uganda',
    weight: 10,
    price: 200,
  },
  {
    parcelId: 25,
    user: {
      id: 2,
    },
    parcelName: 'Men M Cardigan',
    status: 'in transit',
    location: 'Rwanda',
    destination: 'Kenya',
    weight: 10,
    price: 200,
  },
  {
    parcelId: 26,
    user: {
      id: 2,
    },
    parcelName: 'Amazon Kindle',
    status: 'cancelled',
    location: 'Rwanda',
    destination: 'Kenya',
    weight: 10,
    price: 200,
  },
  {
    parcelId: 31,
    user: {
      id: 3,
    },
    parcelName: 'Dictionary',
    status: 'in transit',
    location: 'Rwanda',
    destination: 'Uganda',
    weight: 10,
    price: 200,
  },
  {
    parcelId: 33,
    user: {
      id: 3,
    },
    parcelName: 'HP Spectre',
    status: 'in transit',
    location: 'Rwanda',
    destination: 'Kenya',
    weight: 10,
    price: 200,
  },
  {
    parcelId: 32,
    user: {
      id: 3,
    },
    parcelName: 'Iphone 7',
    status: 'in transit',
    location: 'Nigeria',
    destination: 'Kenya',
    weight: 10,
    price: 200,
  },
];
export default parcels;
